export const RESOURCES: Record<string, { title: string; url: string }> = {
  JavaScript: { title: 'The Modern JavaScript Tutorial', url: 'https://javascript.info/' },
  TypeScript: { title: 'TypeScript Handbook', url: 'https://www.typescriptlang.org/docs/handbook/intro.html' },
  React: { title: 'React Official Docs', url: 'https://react.dev/learn' },
  'Next.js': { title: 'Next.js Learn Course', url: 'https://nextjs.org/learn' },
  'Tailwind CSS': { title: 'Tailwind CSS Docs', url: 'https://tailwindcss.com/docs' },
  HTML: { title: 'MDN HTML Guide', url: 'https://developer.mozilla.org/en-US/docs/Web/HTML' },
  CSS: { title: 'MDN CSS Guide', url: 'https://developer.mozilla.org/en-US/docs/Web/CSS' },
  'Node.js': { title: 'Node.js Official Guides', url: 'https://nodejs.org/en/learn' },
  Express: { title: 'Express.js Guide', url: 'https://expressjs.com/en/starter/guide.html' },
  NestJS: { title: 'NestJS Documentation', url: 'https://docs.nestjs.com/' },
  PostgreSQL: { title: 'PostgreSQL Tutorial', url: 'https://www.postgresqltutorial.com/' },
  MongoDB: { title: 'MongoDB University', url: 'https://university.mongodb.com/' },
  Docker: { title: 'Docker Getting Started', url: 'https://docs.docker.com/get-started/' },
  Git: { title: 'Git Official Book (Pro Git)', url: 'https://git-scm.com/book/en/v2' },
  'REST API': { title: 'REST API Tutorial', url: 'https://restfulapi.net/' },
  Python: { title: 'Python Official Tutorial', url: 'https://docs.python.org/3/tutorial/' },
  SQL: { title: 'SQL Tutorial - W3Schools', url: 'https://www.w3schools.com/sql/' },
  Pandas: { title: 'Pandas Documentation', url: 'https://pandas.pydata.org/docs/getting_started/index.html' },
  NumPy: { title: 'NumPy Quickstart', url: 'https://numpy.org/doc/stable/user/quickstart.html' },
  'Data Analysis': { title: 'Data Analysis with Python (freeCodeCamp)', url: 'https://www.freecodecamp.org/learn/data-analysis-with-python/' },
  'Machine Learning': { title: 'Machine Learning Crash Course (Google)', url: 'https://developers.google.com/machine-learning/crash-course' },
  'Deep Learning': { title: 'Deep Learning Specialization Overview', url: 'https://www.deeplearning.ai/' },
  TensorFlow: { title: 'TensorFlow Tutorials', url: 'https://www.tensorflow.org/tutorials' },
  PyTorch: { title: 'PyTorch Tutorials', url: 'https://pytorch.org/tutorials/' },
  'scikit-learn': { title: 'scikit-learn Getting Started', url: 'https://scikit-learn.org/stable/getting_started.html' },
  NLP: { title: 'NLP Course - Hugging Face', url: 'https://huggingface.co/learn/nlp-course' },
};

export const DEFAULT_RESOURCE = { title: 'Search on freeCodeCamp', url: 'https://www.freecodecamp.org/' };